version: '3'
services:
  mongo:
    container_name: rttma-mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - docker-net
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: foo
      # MONGO_INITDB_ROOT_PASSWORD: bar
    volumes:
      - ./database/mongo/data:/data/db


  redis:
    container_name: rttma-redis
    image: 'redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./database/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - docker-net


  traffic:
    build:
      context: ./src/
      dockerfile: Dockerfile
    container_name: rttma-traffic
    image: traffic
    # environment:
    #   - FLASK_SERVER_PORT=9091
    networks:
      - docker-net
    depends_on:
      - rttma-redis
      - rttma-mongo


  redis-commander:
    container_name: rttma-redis-commander
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    restart: always
    networks:
      - docker-net
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8082:8081"


  mongo-express:
    container_name: rttma-mongo-express
    image: mongo-express
    restart: always
    networks:
      - docker-net
    ports:
        - 8081:8081
    depends_on:
        - rttma-mongo
    environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
        # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
        # ME_CONFIG_MONGODB_ENABLE_ADMIN: true
        # ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME} # mongo-express login username and password.
        # ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}

  nginx:
    container_name: rttma-nginx
    image: nginx:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - docker-net
    ports:
      - $SERVER_HTTP_PORT:80
      - $SERVER_HTTPS_PORT:443
    expose:
      - $SERVER_HTTP_PORT
      - $SERVER_HTTPS_PORT
    depends_on:
      - rttma-traffic
    volumes:
      - ./nginx:/etc/nginx/conf.d
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"


networks:
  docker-net:
    driver: bridge
